Cluster:
  imageHub:
    enable: false
    domain: registry.cn-hangzhou.aliyuncs.com
    namespace: ddd
    password: dd
    username: dd
  etcd:
    enable: false
    endpoints: 
    - 192.168.3.103:2379 
    - 192.168.3.103:2379
    certificate_path:
    secretName: 
  RWX:
    enable: true
    storageClassName:
  RWO:
    enable: true
    storageClassName:
  regionDatabase:
    enable: true
    host: 
    name: 
    password: pd
    port: 330
    username: ro
  atewayIngressIPs:
    ip: 333333
    







Component:
  rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
  installVersion: v5.5.0-release     