Cluster:
## 定义是否开启高可用，true为开，false为关  
  enableHA:
    enable: false
## 定义是否使用外部镜像镜像仓库，true为开，false为关
  imageHub:
    enable: false
    domain: registry.cn-hangzhou.aliyuncs.com
    namespace: ddrainbond
    password: admin
    username: admin
## 外部ETCD，对应填写IP，证书，true为开，false为关
  etcd:
    enable: false
    endpoints: 
    - 192.168.3.103:2379 
    - 192.168.3.103:2379
    - 192.168.3.103:2379
    secretName: 
## 外部存储，直接填写storageClassName，true为开，false为关
  RWX:
    enable: false
    storageClassName: glusterfs-simple
## 外部存储，直接填写storageClassName，true为开，false为关
  RWO:
    enable: false
    storageClassName: glusterfs-simple
## 数据库，true为开，false为关
  regionDatabase:
    enable: false
    host: 88888
    name: database name
    password: admin
    port: 3306
    username: admin
## 数据库，true为开，false为关
  uiDatabase:
    enable: false
    host: 172.36.22.10
    name: database name
    password: admin
    port: 3306
    username: admin 
## 对外网关，填写IP
  gatewayIngressIPs:
    ip: 172.36.22.10 
## chaos对应配置，name为Chaos节点node名称
  nodesForChaos:
  - name: 47.105.55.170
  - name: 47.105.55.175

## 网关节点对应配置，externalIP为网关节点外部IP，internalIP为网关节点内部IP，name为网关节点node名称
  nodesForGateway:
  - externalIP: 47.105.55.170
    internalIP: 172.31.112.134
    name: 47.105.55.170
  - externalIP: 47.105.55.171
    internalIP: 172.31.112.135
    name: 47.105.55.175
 
    






Component:
## 系统组件统一镜像仓库拉取地址及名称空间
  rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
## 系统组件统一镜像版本
  installVersion: v5.5.0-release
## 系统组件统一镜像拉取策略
  imagePullPolicy: IfNotPresent
## 高可用安装模式下，系统组件副本数
  replicas: 2
## rbd-api 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_api:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
#### 环境变量test为key,5555为value
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-gteway 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_gteway:
    args:
  ##    - --gteway-ca=/r
  ##    - --gteway-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-node 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_node:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-hub 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_hub:
    args:
  ##    - --hub-ca=/r
  ##    - --hub-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-mq 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_mq:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-resource-proxy 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_resource_proxy:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-webcli 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_webcli:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-monitor 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_monitor:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-db 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_db:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-chaos 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_chaos:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-worker 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_worker:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image: 
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-eventlog 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载      
  rbd_eventlog:
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
  ##  image:
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## rbd-app-ui 组件自定义信息：启动参数，环境变量，镜像地址，存储挂载
  rbd_app_ui:
    enable: true
    args:
  ##    - --etcd-ca=/r
  ##    - --etcd-ca=/r
  ##  env:
  ##    test: 5555
  ##    test2: 6666
    image: registry.cn-hangzhou.aliyuncs.com/yangkaa/rainbond:helm-allinone
  ##  volumes:
  ##    testpv:
  ##      persistentVolumeClaim:
  ##        claimName: rbd-cpt-grdate
  ##    testsc:
  ##      secret:
  ##        defaultMode: 420
  ##        secretName: rbd-api-server-cert
  ##  volumeMounts:
  ##    testpv: /data
  ##    testsc: /test
## nfs-provisioner 组件自定义信息：镜像地址
  nfs_provisioner:
    image:
## rbd-etcd 组件自定义信息：镜像地址
  rbd_etcd:
    image:
## metrics-server 组件自定义信息：镜像地址
  metrics_server:
    image:
## dashboard-metrics-scraper 组件自定义信息：镜像地址
  dashboard_metrics_scraper:
    image:
## kubernetes-dashboard 组件自定义信息：镜像地址
  kubernetes_dashboard:
    image: