apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RainbondCluster
  metadata:
    name: rainbondcluster
    namespace: rbd-system
  spec:
    enableHA: true
{{- if .Values.Cluster.etcd.enable "true "  }}    
    etcdConfig:
      endpoints: 
      {{- range .Values.Cluster.etcd.endpoints }}
      - {{ . | title  }}
      {{- end }}    
      secretName: rbd-etcd-secret
{{- end }}  
    gatewayIngressIPs:
    - 47.105.55.170
{{- if .Values.Cluster.imageHub.enable  }}
    imageHub:
      domain: "goodrain.me“
      password: "d0d"
      username: "admin"
{{- end }}
    rainbondVolumeSpecRWO:
      csiPlugin: {}
      imageRepository: ""
      storageClassParameters: {}
{{- if .Values.Cluster.RWX.enable  }} 
    rainbondVolumeSpecRWX:
      storageClassName: glusterfs-simple
      csiPlugin: 
    	    aliyunNas: {}
{{- end }}          
    storageClassParameters: 
    	  parameters: 
    	    volumeAs: subpath
    	    server: xxx.nas.server.dddd.com
    	    archiveOnDelete: true
{{- if .Values.Cluster.regionDatabase.enable  }}
  regionDatabase:
    host: 172.20.251.91
    name: rbdregion
    password: password
    port: 3306
    username: root
{{- end }}
  suffixHTTPHost: 5-3-0.goodrain.org
    installMode: WithoutPackage
    installVersion: v5.5.0-release
    nodesForChaos:
    - externalIP: 47.105.55.170
      internalIP: 172.17.0.2
      name: node
    nodesForGateway: 
    - externalIP: 47.105.55.170
      internalIP: 172.17.0.2
      name: node
    rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
    suffixHTTPHost: grapps.cn

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
