apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RainbondCluster
  metadata:
    name: rainbondcluster
    namespace: rbd-system
  spec:
    enableHA: {{ .Values.Cluster.enableHA.enable }}
{{- if or .Values.Cluster.etcd.enable  .Values.Cluster.enableHA.enable }}    
    etcdConfig:
      endpoints: 
      {{- range .Values.Cluster.etcd.endpoints }}
      - {{ . | toString  }}
      {{- end }}    
      secretName: {{ .Values.Cluster.etcd.secretName }}
{{- end }}
    configCompleted: true
    gatewayIngressIPs:
    - {{ .Values.Cluster.gatewayIngressIPs.ip }}
{{- if .Values.Cluster.imageHub.enable  }}
    imageHub:
      domain: {{ .Values.Cluster.imageHub.domain }}
      password: {{ .Values.Cluster.imageHub.password }}
      username: {{ .Values.Cluster.imageHub.username }}
      namespace: {{ .Values.Cluster.imageHub.namespace }} 
{{- end }}
{{- if .Values.Cluster.RWO.enable  }} 
    rainbondVolumeSpecRWO:
      storageClassName: {{ .Values.Cluster.RWO.storageClassName }}
{{- end }}
{{- if .Values.Cluster.RWX.enable  }} 
    rainbondVolumeSpecRWX:
      storageClassName: {{ .Values.Cluster.RWX.storageClassName }}         
{{- end }}
{{- if or .Values.Cluster.regionDatabase.enable  .Values.Cluster.enableHA.enable }}
    regionDatabase:
      host: {{  required ".Values.Cluster.regionDatabase.host cannot be empty!" .Values.Cluster.regionDatabase.host }}
      name: {{ .Values.Cluster.regionDatabase.name }}
      password: {{ .Values.Cluster.regionDatabase.password }}
      port: {{ .Values.Cluster.regionDatabase.port }}
      username: {{ .Values.Cluster.regionDatabase.username }}
{{- end }}
{{- if or .Values.Cluster.uiDatabase.enable .Values.Cluster.enableHA.enable }}
    uiDatabase:
      host: {{ .Values.Cluster.uiDatabase.host }}
      name: {{ .Values.Cluster.uiDatabase.name }}
      password: {{ .Values.Cluster.uiDatabase.password }}
      port: {{ .Values.Cluster.uiDatabase.port }}
      username: {{ .Values.Cluster.uiDatabase.username }}
{{- end }}
    suffixHTTPHost: ""
    installMode: WithoutPackage
    installVersion: {{ .Values.Component.installVersion }}     
    nodesForChaos:
{{ .Values.Cluster.nodesForChaos | toYaml | indent 4 }}   
    nodesForGateway: 
{{ .Values.Cluster.nodesForGateway | toYaml | indent 4 }}
    rainbondImageRepository: {{ .Values.Component.rainbondImageRepository }}

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
