apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RainbondCluster
  metadata:
    name: rainbondcluster
    namespace: rbd-system
  spec:
    enableHA: true
{{- if .Values.Cluster.etcd.enable }}    
    etcdConfig:
      endpoints: 
      {{- range .Values.Cluster.etcd.endpoints }}
      - {{ . | title  }}
      {{- end }}    
      secretName: {{- .Values.Cluster.etcd.secretName }}
{{- end }}  
    gatewayIngressIPs:
    {{- range .Values.Cluster.atewayIngressIPs.ip }}
      - {{ . | title  }}
{{- if .Values.Cluster.imageHub.enable  }}
    imageHub:
      domain: {{- .Values.Cluster.imageHub.domain }}
      password: {{- .Values.Cluster.imageHub.password }}
      username: {{- .Values.Cluster.imageHub.username }}
      namespace: {{- .Values.Cluster.imageHub.namespace }} 
{{- end }}
{{- if .Values.Cluster.RWO.enable  }} 
    rainbondVolumeSpecRWO:
      csiPlugin: {}
      imageRepository: ""
      storageClassParameters: {{- .Values.Cluster.RWO.storageClassName }}
{{- end }}
{{- if .Values.Cluster.RWX.enable  }} 
    rainbondVolumeSpecRWX:
      storageClassName: {{- .Values.Cluster.RWX.storageClassName }}         
    storageClassParameters: 
    	  parameters: 
    	    volumeAs: subpath
    	    server: xxx.nas.server.dddd.com
    	    archiveOnDelete: true
{{- end }}
{{- if .Values.Cluster.regionDatabase.enable  }}
    regionDatabase:
      host: {{- .Values.Cluster.regionDatabase.host }}
      name: {{- .Values.Cluster.regionDatabase.name }}
      password: {{- .Values.Cluster.regionDatabase.password }}
      port: {{- .Values.Cluster.regionDatabase.port }}
      username: {{- .Values.Cluster.regionDatabase.username }}
{{- end }}
    suffixHTTPHost: 5-3-0.goodrain.org
      installMode: WithoutPackage
      installVersion: v5.5.0-release
    nodesForChaos:
    - externalIP: 47.105.55.170
      internalIP: 172.17.0.2
      name: node
    nodesForGateway: 
    - externalIP: 47.105.55.170
      internalIP: 172.17.0.2
      name: node
    rainbondImageRepository: registry.cn-hangzhou.aliyuncs.com/goodrain
    suffixHTTPHost: grapps.cn

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
