{{- if or .Values.Cluster.etcd.enable  .Values.Cluster.enableHA.enable  }}
{{ else }}
apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-etcd
      priorityComponent: "true"
    name: rbd-etcd
    namespace: rbd-system
  spec:
    image: {{ .Values.Component.rainbondImageRepository }}/etcd:v3.3.18
    imagePullPolicy: {{ .Values.Component.imagePullPolicy }}
    priorityComponent: true
      replicas: 1
 {{- end }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-gateway
      priorityComponent: "true"
    name: rbd-gateway
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_gteway.args }}
    args:
    {{- range .Values.Component.rbd_gteway.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_gteway.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_gteway.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_gteway.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_gteway.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_gteway.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_gteway.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-gateway:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: true
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-node
      persistentVolumeClaimAccessModes: ReadWriteOnce
      priorityComponent: "true"
    name: rbd-node
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_node.args }}
    args:
    {{- range .Values.Component.rbd_node.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_node.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_node.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_node.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_node.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_node.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_node.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-node:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: true
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-hub
      persistentVolumeClaimAccessModes: ReadWriteOnce
      priorityComponent: "true"
    name: rbd-hub
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_hub.args }}
    args:
    {{- range .Values.Component.rbd_hub.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_hub.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_hub.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/registry:2.6.2
    imagePullPolicy: IfNotPresent
    priorityComponent: true
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: metrics-server
    name: metrics-server
    namespace: rbd-system
    resourceVersion: "1154"
    uid: bf4b41e2-ad73-4601-a7ee-d58b65e8abf8
  spec:
    image: {{ .Values.Component.rainbondImageRepository }}/metrics-server:v0.3.6
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-mq
    name: rbd-mq
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_mq.args }}
    args:
    {{- range .Values.Component.rbd_mq.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_mq.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_mq.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_mq.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_mq.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_mq.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_mq.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-mq:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-resource-proxy
    name: rbd-resource-proxy
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_resource_proxy.args }}
    args:
    {{- range .Values.Component.rbd_resource_proxy.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_resource_proxy.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_resource_proxy.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-resource-proxy:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1 
      
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-webcli
    name: rbd-webcli
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_webcli.args }}
    args:
    {{- range .Values.Component.rbd_webcli.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_webcli.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_webcli.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_webcli.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_webcli.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_webcli.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_webcli.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-webcli:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: dashboard-metrics-scraper
    name: dashboard-metrics-scraper
    namespace: rbd-system
  spec:
    image: {{ .Values.Component.rainbondImageRepository }}/kubernetes-dashboard:v2.0.1-3
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-monitor
    name: rbd-monitor
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_monitor.args }}
    args:
    {{- range .Values.Component.rbd_monitor.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_monitor.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_monitor.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_monitor.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_monitor.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_monitor.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_monitor.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-monitor:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

{{- if or .Values.Cluster.regionDatabase.enable  .Values.Cluster.enableHA.enable  }}
{{ else }}
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-db
    name: rbd-db
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_db.args }}
    args:
    {{- range .Values.Component.rbd_db.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_db.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_db.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_db.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_db.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_db.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_db.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-db:8.0.19
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      replicas: 1
{{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-chaos
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-chaos
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_chaos.args }}
    args:
    {{- range .Values.Component.rbd_chaos.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_chaos.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_chaos.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_chaos.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_chaos.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_chaos.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_chaos.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-chaos:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-worker
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-worker
    namespace: rbd-system
  spec:
    env:
    - name: ALLINONE_MODE
      value: "true"
    {{- if .Values.Component.rbd_hub.args }}
    args:
    {{- range .Values.Component.rbd_hub.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_hub.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_hub.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-worker:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-eventlog
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-eventlog
    namespace: rbd-system
  spec:
    {{- if .Values.Component.rbd_hub.args }}
    args:
    {{- range .Values.Component.rbd_hub.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_hub.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_hub.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_hub.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_hub.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-eventlog:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-api
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-api
    namespace: rbd-system
  spec:  
    {{- if .Values.Component.rbd_api.args }}
    args:
    {{- range .Values.Component.rbd_api.args }}
    - {{ . | toString  }}
    {{- end }} 
    {{- end }}
    {{- if .Values.Component.rbd_api.env }}
    env:
    {{- range $key,$value := .Values.Component.rbd_api.env }}
    - name: {{ $key }}
      value: {{ $value }}
    {{- end }}
    {{- end }}
    {{- if .Values.Component.rbd_api.volumeMounts }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_api.volumeMounts }}
    - name: {{ $key }}
      mountPath: {{ $value }}
    {{- end }}  
    {{- end }}
    {{- if .Values.Component.rbd_api.volumes }}
    volumeMounts:
    {{- range $key,$value := .Values.Component.rbd_api.volumes }}
    - name: {{ $key }}
{{ $value | toYaml |indent 6}}
    {{- end }}  
    {{- end }}
    image: {{ .Values.Component.rainbondImageRepository }}/rbd-api:{{ .Values.Component.installVersion }}
    imagePullPolicy: IfNotPresent
    priorityComponent: false
      {{- if .Values.Cluster.enableHA.enable  }} 
      replicas: {{- .Values.Component.replicas }}
      {{ else }}
      replicas: 1
      {{- end }}


kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
