apiVersion: v1
items:
- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-etcd
      priorityComponent: "true"
    name: rbd-etcd
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/etcd:v3.3.18
    imagePullPolicy: IfNotPresent
    priorityComponent: true
    replicas: 1


- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-gateway
      priorityComponent: "true"
    name: rbd-gateway
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-gateway:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: true
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-node
      persistentVolumeClaimAccessModes: ReadWriteOnce
      priorityComponent: "true"
    name: rbd-node
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-node:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: true
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-hub
      persistentVolumeClaimAccessModes: ReadWriteOnce
      priorityComponent: "true"
    name: rbd-hub
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/registry:2.6.2
    imagePullPolicy: IfNotPresent
    priorityComponent: true
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: metrics-server
    name: metrics-server
    namespace: rbd-system
    resourceVersion: "1154"
    uid: bf4b41e2-ad73-4601-a7ee-d58b65e8abf8
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/metrics-server:v0.3.6
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-mq
    name: rbd-mq
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-mq:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-resource-proxy
    name: rbd-resource-proxy
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-resource-proxy:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-webcli
    name: rbd-webcli
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-webcli:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: dashboard-metrics-scraper
    name: dashboard-metrics-scraper
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/metrics-scraper:v1.0.4
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: kubernetes-dashboard
    name: kubernetes-dashboard
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/kubernetes-dashboard:v2.0.1-3
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-monitor
    name: rbd-monitor
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-monitor:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-db
    name: rbd-db
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-db:8.0.19
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-chaos
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-chaos
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-chaos:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-worker
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-worker
    namespace: rbd-system
  spec:
    env:
    - name: ALLINONE_MODE
      value: "true"
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-worker:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-eventlog
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-eventlog
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-eventlog:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

- apiVersion: rainbond.io/v1alpha1
  kind: RbdComponent
  metadata:
    labels:
      belongTo: rainbond-operator
      creator: Rainbond
      name: rbd-api
      persistentVolumeClaimAccessModes: ReadWriteOnce
    name: rbd-api
    namespace: rbd-system
  spec:
    image: registry.cn-hangzhou.aliyuncs.com/goodrain/rbd-api:v5.5.0-release
    imagePullPolicy: IfNotPresent
    priorityComponent: false
    replicas: 1

kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
